### ISSUE TITLE
Feature request: Add the title for content container in post

### ISSUE THREAD

**Issue by haonanzzz** [info442-su23/e-team#100]

**Comment by haonanzzz** [comment]
- there is no title for the content container, which is showing the date, location, and time
- having a title can help user being clear about what the information about: is it a post information, or a painting information

**Comment by VictoriaVVei** [comment]
> * there is no title for the content container, which is showing the date, location, and time
> * having a title can help user being clear about what the information about: is it a post information, or a painting information

Thanks for mentioning. But currently we may not consider to add this. It may be a little mess to revise a lot css.

**Comment by cherimarie** [comment]
This should be labeled "wontfix", not "invalid." The suggestion is valid, but it's not something your team is choosing to do at this time.
