### ISSUE TITLE
Request feature : Website icon is react app default, can have a new unique one

### ISSUE THREAD

**Issue by haonanzzz** [info442-su23/e-team#105]
- Website icon is the default one from react, not displaying the one that fit with the website; expect to see a one that is unique
- helpful for users to identify the webapp and have remarkable memories to it

**Comment by VictoriaVVei** [comment]
We actually have one.
![810B82AA-85EC-4FE6-BCA7-D60F13710778](https://github.com/info442-su23/e-team/assets/91993339/fab4b783-c23e-4932-9aa2-918a4e7abda9)
