### ISSUE TITLE
First image on Home Screen does not show full words- minor 

### ISSUE THREAD

**Issue by Ghermo35** [info442-su23/e-team#108]
![C65F8BCB-0E5F-4978-8D79-E5CD10C2C336](https://github.com/info442-su23/e-team/assets/43656152/c0f5f7c9-541a-4eb9-b078-f585ebb1eb45)

the first image when opening app on mobile doesn’t show the whole words and image. I’m on a iPhone 14 
Other than that functions work very well. Easy minor fix.

**Comment by MarinaCui** [comment]
Thank you for pointing out that! Because “@media” is optional, we don't consider the layout of the web page on a mobile phone. Therefore, we focused our energy on the computer side. 

Similar to #83

**Comment by Zuoooooo** [comment]
Duplicate #83 #88
