### ISSUE TITLE
Display All Page Numbers (Feature request)

### ISSUE THREAD

**Issue by DongTianjia** [info442-su23/e-team#109]
It would be really useful if the user could see all possible page numbers so that they know when there are no more pages to stop clicking on the next page. It would be nice to have all page numbers listed in the middle (in between last and next page button). 

<img width="1280" alt="Screen Shot 2023-08-09 at 13 50 09" src="https://github.com/info442-su23/e-team/assets/87292522/48d58d0b-600e-4f76-aa11-04fad69c6c89">

**Comment by VictoriaVVei** [comment]
Thanks for mentioning. We may revise this later.

**Comment by VictoriaVVei** [comment]
Deployed in #113
