### ISSUE TITLE
Minor Bug: Whitespace on the right side of the main page on mobile screens

### ISSUE THREAD

**Issue by asingh0725** [info442-su23/e-team#83]
Summary:
- When I switched to phone-size screens on the browsers developer tools, I notice a whitespace on the right side of the screen on the main page.

Environment: MacOS Google Chrome

Steps to Reproduce: Open the website URL, inspect on Chrome, and select any phone-sized screen size in the developer tool options.

Actual result: Whitespace on the right side of the screen.

Expected result: The background navbar image extends the full width of the screen.

**Comment by Zuoooooo** [comment]
Because “@media” is optional, we don't consider the layout of the web page on a mobile phone. Therefore, we focused our energy on the computer side. Thank you.

**Comment by cherimarie** [comment]
This should be labeled "wontfix", not "invalid." The suggestion is valid, but it's not something your team is choosing to do at this time.
