### ISSUE TITLE
Minor Bug: Search Bar on Diversity Page is distorted for mobile sized screens

### ISSUE THREAD

**Issue by asingh0725** [info442-su23/e-team#88]
Summary:

When I switched to phone-size screens on the browser developer tools, I notice that on the diversity page, the type field distorts on small screen sizes with the x icon wrapping to the next line.
Environment: MacOS Google Chrome

Steps to Reproduce: Open the website URL, inspect on Chrome, and select any phone-sized screen size in the developer tool options, click on one of the options on the main page, and look at the diversity page's search field

Actual result: The search field is distorted.

Expected result: The search field will stay in the same line alignment.

<img width="378" alt="Screenshot 2023-08-08 at 5 35 52 PM" src="https://github.com/info442-su23/e-team/assets/70999719/98804672-faf4-4fb3-aa7b-6cd2a4ff13a0">

**Comment by VictoriaVVei** [comment]
Since the media is optional, we don't consider the mobile end.

**Comment by MarinaCui** [comment]
Duplicate with #83 and #108
