### ISSUE TITLE
Diversity Page Last and Next Page Buttons don't work - Bug Minor

### ISSUE THREAD

**Issue by BrookePedersen** [info442-su23/e-team#91]
Bug: minor
general summary of the problem: the buttons to navigate pages within the diversity tab doesn't work.
steps to reproduce: adding an on-click to each button to allow navigation for users
expected result: to move to another page, either back or forward
actual result: nothing

**Comment by syd-moral** [comment]
The buttons don't work on the profile page as well

**Comment by VictoriaVVei** [comment]
We do not have enough posts for switching page in diversity page. If there are more than 9 posts, then you can switch. Otherwise, can't. We current only have less than 9 page.

**Comment by VictoriaVVei** [comment]
> The buttons don't work on the profile page as well

If there are more than 6 posts, then you can switch. Otherwise, can't. We current only have less than 9 page. You can like some posts or make posts.
