### ISSUE TITLE
Login with Google failure- Bug Minor

### ISSUE THREAD

**Issue by BrookePedersen** [info442-su23/e-team#94]
Bug: minor
general summary of the problem: when attempting to log in with google it says "do not support currently"
steps to reproduce: add an extension with firebase to allow login with Gmail.
expected result: to have a pop-up that shows my Gmail login information
actual result: red flag stating "do not support currently"
<img width="1440" alt="Screen Shot 2023-08-08 at 5 45 42 PM" src="https://github.com/info442-su23/e-team/assets/84031057/1267ceb1-a6ed-4545-ad68-5c6b6fdaf055">

**Comment by Zuoooooo** [comment]
We do not support google login, because this requires money. After discussing with the professor, we think this is an impossible feature. Therefore, when a user logs in with google it will say "do not support currently" to prompt the user.

**Comment by cherimarie** [comment]
This is a valid bug, and I'd say it's a major one. The button to log in with google is present, users have an expectation it should work. To address this bug, the button should be removed.
