### ISSUE TITLE
Example culture panel/placeholder text is still present in festival page (Minor Bug)

### ISSUE THREAD

**Issue by bonglrob** [info442-su23/e-team#96]
Expected: Culture Example page to be removed
Actual: culture example page 

Env: Brave Browser/Chrome v1.56.20, Acer Windows 11 Desktop

![brave_OMSb1DAZQF](https://github.com/info442-su23/e-team/assets/8757841/52b0421e-d9c8-4612-976a-f7fce867e6d5)

**Comment by VictoriaVVei** [comment]
This is created by professor so we didn't delete it.
