### ISSUE TITLE
Feature Request: Q&A page

### ISSUE THREAD

**Issue by ericagordy** [info442-su23/e-team#98]
On the first question "why i load so slowly", the answer is very technical. For someone who does not understand programming there should be a more simple explanation. Also, it should be worded as a question, like, "Why is the page taking a long time to load?" 
<img width="823" alt="Screenshot 2023-08-08 at 5 55 02 PM" src="https://github.com/info442-su23/e-team/assets/66372667/b407da04-d726-4374-8a37-4590aaabc46d">

**Comment by VictoriaVVei** [comment]
Thanks for mentioning. We may add this later.

**Comment by siyuanji1** [comment]
Text change for Q&A pages helps user have better understand for the question.
