### ISSUE TITLE
Search bar cannot add new filters (Minor bug)

### ISSUE THREAD

**Issue by FastFusion5** [info442-su23/e-team#99]
After removing a filter option from the search bar, it becomes inactive and I cannot add new filters to it. I have to return to the main page to re-select a new filter. I initially expected it to be able to add new filters on the diversity page directly so I don't have to go back. Currently, I need to go back to the "Enrich Culture" page which is quite inconvenient.
<img width="796" alt="Screenshot 2023-08-09 at 8 55 00 AM" src="https://github.com/info442-su23/e-team/assets/77070825/32394896-d330-4dd8-a7a0-23c234113958">

**Comment by VictoriaVVei** [comment]
This is actually what we design. You can only filter from main page.
